### ISSUE TITLE
missing 1 required positional argument: 'ventilation'

### ISSUE THREAD

**Issue by Ragnarox666** [serbanb11/bosch-homecom-hass#67]
Hi everybody and a happy new year,

i recently tried to add my K40 with Bosch HomeCom.
Everything worked well so far, until the Addon tries to initialize.

As i am new to github, i am not sure how to report the issue correctly?

In the Addon i only get this error:
Bosch HomeCom Einrichtungsfehler, wird erneut versucht: BHCDeviceK40.__init__() missing 1 required positional argument: 'ventilation'

I hope you can help?

Thanks in advance 
Stephan

**Comment by Ragnarox666** [comment]
Hi,

yes i'm sorry, my fault. i thought i had the latest version. i had 1.3.10.
After upgrading to 1.3.19 everything is fine.
Many thanks!
